### ISSUE TITLE
How to resize the resolution of the pdf file

### ISSUE THREAD

**Issue by shafiemukhre** [jgazeau/website2pdf#30] opened 2022-05-21 02:26 UTC
Thank you so much for creating this! I'm currently using this in my hugo site and the output resolution of the pdf file is 594px x 841px. I'm not sure if this is the default size in order for the content to fit in the standard 8.5 × 11 inches US paper size. The contents seems small and I'm wondering if there's a way to resize the output so that we can reduce the output pdf's pages for each webpage?

**Comment by jgazeau** [comment] 2022-05-22 08:12
Hi @shafiemukhre , 
Glad you use this lib 😃 
Actually, the lib should print 1 pdf page for each webpage you have (depending on your media rules).
Also because I'm not using the [preferCSSPageSize ](https://devdocs.io/puppeteer/index#pagepdfoptions), and using the A4 format by default (`A4: 8.27in x 11.7in`), your webpage should scale to fit one pdf page.

What you can do is actually check the print preview of your Hugo website in a browser (with `printbackground` option and A4 format) as it will be the same as the website2pdf output.

If you already don't have the appropriate one in your browser, I think that you'll have to use the css media rules.
For example to add a pagebreak you can add this kind of code:
```
<div class='pagebreak'></div>

.pagebreak {
  @media print
    break-after: page
}
```
Kr,

**Comment by jgazeau** [comment] 2022-08-02 21:15
Hi @shafiemukhre , any news regarding your issue ?
Also don't hesitate to provide a reproducer so I can help you more.
If you don't require any additionnal help I'll close this issue.

**Closed** 2022-08-11 09:24 UTC
Labels: help wanted
